name: Fetch Skype Group Messages

on:
  schedule:
    - cron: '0 1 * * *'  # Chạy mỗi ngày lúc 1 AM UTC
  workflow_dispatch:  # Cho phép chạy thủ công từ tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Python Setup & Packages Installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > account.json

      - name: Execute Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute heulwen-bot_crawl_data_from_skype_group.ipynb
        shell: bash
