name: Fetch Skype Group Messages

on:
  schedule:
    - cron: '0 1 * * *'  # Chạy mỗi ngày lúc 1 AM UTC
  workflow_dispatch:  # Cho phép chạy thủ công từ tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository
      - name: Fetch repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Python và các thư viện cần thiết
      - name: Python Setup & Packages Installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'  # caching pip dependencies

      # Bước 3: Cài đặt các thư viện từ requirements.txt
      - run: pip install -r requirements.txt

      # Bước 4: Chạy Jupyter notebook
      - name: Execute Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute heulwen-bot_crawl_data_from_skype_group.ipynb
        shell: bash
